version: "3.8"

services:
  app:
    container_name: dev-blog-django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: dev-blog-postgres
    image: postgres:15.2
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  dev_postgres_data:
