version: "3.11"

services:
  app:
    container_name: blog-django
    build: .
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - db
      - redis

  db:
    container_name: blog-postgres
    image: postgres:15.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    container_name: blog-redis
    image: redis:7

  celery:
    container_name: blog-celery
    build: .
    restart: always
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app

  nginx:
    container_name: blog-nginx
    build: ./nginx
    restart: always
    environment:
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume:
