version: "3.8"

networks:
  netapp:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16

volumes:
  static_volume:
  media_volume:
  pgmaster_data:
  pgadmin_data:
  redis_data:
  prometheus_data:
  alertmanager_data:
  grafana_data:

services:
  app:
    build: .
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    env_file:
      - ./.env
    networks:
      - netapp
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/mediafiles/
    depends_on:
      - pgmaster
      - redis

  pgmaster:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - pgmaster_data:/var/lib/postgresql/data/
      - ./scripts/psql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - netapp
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - PGADMIN_DEFAULT_EMAIL=${USER_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${USER_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    networks:
      - netapp
    expose:
      - 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin/
    depends_on:
      - pgmaster

  redis:
    image: redis:7
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    networks:
      - netapp
    expose:
      - 6379
    volumes:
      - redis_data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - netapp
    expose:
      - 8081
    depends_on:
      - redis

  celery:
    build: .
    restart: unless-stopped
    command: celery -A config worker -l info
    env_file:
      - ./.env
    networks:
      - netapp
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - netapp
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    restart: unless-stopped
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status'
    networks:
      - netapp
    expose:
      - 9113

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://localhost/prometheus/'
    networks:
      - netapp
    expose:
      - 9090
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    depends_on:
      - app
      - node-exporter
      - nginx-exporter

  alert-manager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    command: '--config.file=/config/alertmanager.yml --log.level=debug'
    env_file:
      - ./.env
    networks:
      - netapp
    expose:
      - 9093
    volumes:
      - ./alertmanager:/config
      - alertmanager_data:/data
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${USER_NAME}
      - GF_SECURITY_ADMIN_PASSWORD=${USER_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - netapp
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  nginx:
    build: ./nginx
    restart: unless-stopped    
    networks:
      - netapp
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/mediafiles/
    depends_on:
      - app
