global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  # - alert.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

scrape_configs:
  - job_name: django
    static_configs:
      - targets:
          - 'app:8000'