global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alert-manager:9093']

scrape_configs:
  - job_name: django-app-metrics
    static_configs:
      - targets: ['app:8000']

  - job_name: linux-host-metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: nginx-stub-metrics
    static_configs:
      - targets: ['nginx-exporter:9113']
